theme: minima
title: A Walk Through the Theory and Implementation of AI
author: Yang Yao
description: To help others understand step by step how the theory behind methods and algorithms are derived and providing a implementation in code.
